### ISSUE TITLE
When i disable "transparent BG" in megahack while using the extension, the game crashes when i leave the main menu

### ISSUE THREAD

**Issue by millionsofplayers** [Ikszyon/UI-Recolor#1]
This fixes itself when i disable the extension, deleting the ui recolor txt doesn't fix this either.

https://user-images.githubusercontent.com/15851867/189991978-349b0e88-7ed5-44bc-a3d8-3800c2dd8764.mp4

**Comment by Ikszyon** [comment]
Will fix this as soon as possible but for the time being you can set the Menu BG‘s color to #FFFFFF. This has the same effect as enabling Transparent BG and won‘t crash if you disable it.
